version: '3'
services:
  shop-web:
    container_name: shop-web
    hostname: shop-web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 5173:5173